### ISSUE TITLE
orm.Connector

### ISSUE THREAD

**Issue by Izanami** [APau17/autoconcept-app#6]
Attributes with accessor
===================
@Mathias64 

* [x] uri
* [x] user
* [x] password

Methods
=======
@kells64000 

Constructor
---------------
* [x] Load driver MySql
* [x] Fake auth

**Comment by kells64000** [comment]
bug a résourdre : test maven du connecteur fonctionne sauf qu'une erreur se produit au bout de quelques secondes !
